[package]
name = "do_good"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "do_good"

[dependencies]
soroban-sdk = { version = "21.6.0", default-features = false, features = ["alloc"] }
